baseurl: /content-guide
markdown: kramdown
name: City of Lexington Content Guide
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty
highlighter: pygments

# Author/Organization info to be displayed in the templates
author:
  name: City of Lexington
  url: http://lexingtonky.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: assets/img/lexington-logo.png
logoalt: Lexington Kentucky Logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Addresses
  url: addresses/
  internal: true
- text: Acronyms and Abbreviations
  url: acronyms-and-abbreviations/
  internal: true
- text: Capitalization
  url: capitalization/
  internal: true
- text: Easily Confused Words
  url: easily-confused-words/
  internal: true
- text: Links
  url: links/
  internal: true
- text: Numbers
  url: numbers/
  internal: true
- text: Place
  url: place/
  internal: true
- text: Plain English
  url: plain-english
  internal: true
- text: Punctuation
  url: punctuation/
  internal: true
- text: Quick Reference
  url: quick-reference/
  internal: true  
- text: Time and Dates
  url: times-and-dates/
  internal: true
- text: Titles
  url: titles/
  internal: true

repos:
- name: City of Lexington Content Guide
  description: Main repository
  url: https://github.com/lfucg/content-guide

# Style Variables
brand_color: "#1188ff"

google_analytics_ua: UA-50592121-14
